version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.20
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 ../deployment_package.zip .
      - zip -g deployment_package.zip getCourses.go
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name getCourses --zip-file fileb://deployment_package.zip
      - echo "DONE!!"